name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '14'

      # 安装和构建
      - name: Install and Build
        run: |
            npm i
            npm run build

      - name: Update dist folder to repository
        env:
            # 仓库用户名
            REPO_USERNAME: "uoau"
            # GitHub Pages仓库名
            DIST_REPO: "utils-hub"
            # GitHub Token
            GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

        run: |
            git config --global user.email "Action@GitHub.com"
            git config --global user.name "GitHub Action"

            git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
            git push --force --quiet "https://$GITHUB_TOKEN@github.com/$REPO_USERNAME/$DIST_REPO.git" master:master